Add 2021 CEPCI Value
IDAES/idaes-pse pull request #1052
Opened 2022-12-15 16:53 UTC by bpaul4

## Fixes

## Summary/Motivation:

## Changes proposed in this PR:
- Adding `USD_2021` units to the IDAES currency dictionary, as these units will be required for applications in other subtasks.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-12-15 16:59 UTC, andrewlee94 requested changes
1. Just to check, can you provide a reference for this value?
2. You need to update the tests to cover this new entry.

2022-12-15 17:51 UTC, bpaul4 commented
1. I double checked the source, and updated it accordingly to use the full year aggregate and not just a partial year estimate. I added the source to the docstring.
2. I added the new entry to the test file.

2022-12-15 17:57 UTC, andrewlee94 approved these changes

2022-12-16 14:48 UTC, anujad95 approved these changes

2022-12-16 16:23 UTC, merged