Update docs to use IDAES/examples instead of IDAES/examples-pse
IDAES/idaes-pse pull request #1132
Opened 2023-03-14 18:00 UTC by dangunter

Fixes #1131 

## Summary/Motivation:
Documentation needs to point to the new examples

## Changes proposed in this PR:
- Fix links and associated description
- Update installation steps

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2023-03-16 19:43 UTC, ksbeattie commented
Nitpick: I kinda liked the diataxis table with the somewhat smaller fonts...

2023-04-07 13:30 UTC, andrewlee94 commented
@dangunter It looks like the docs build for this PR has expired; could you fix the conflict so that the docs can be rebuilt. Note that our supported Python versions are now 3.8-3.11.

2023-04-20 22:01 UTC, dangunter commented
@andrewlee94 @MAZamarripa and @lbianchi-lbl this is ready for review now

2023-04-21 12:31 UTC, andrewlee94 requested changes
Only one minor comment on updating the supported Python versions, but otherwise looks good to me.

2023-04-21 20:52 UTC, dangunter commented on docs/conf.py
> +.. |python-min| replace:: 3.7
there seems to be a second way to do all these replacements in the class RobustReplacements. I don't really understand why that's there (not impossible it's my doing, but I don't remember why if so). @lbianchi-lbl is this something you know more about?

2023-04-21 21:02 UTC, lbianchi-lbl commented on docs/conf.py
> +.. |python-min| replace:: 3.7
Yeah, the simple (ie non-`Robust`) replacements are not expanded in code blocks, and we need the python version to be templated for `conda install python=3.X` commands.

2023-04-21 23:41 UTC, dangunter commented on docs/conf.py
> +.. |python-min| replace:: 3.7
I updated it so they both use the same version constants

2023-04-24 12:30 UTC, andrewlee94 approved these changes

2023-04-27 21:19 UTC, ksbeattie approved these changes
LGTM

2023-04-28 19:45 UTC, merged