Power plant library: drum1D and waterpipe models, tests, and documentation
IDAES/idaes-pse pull request #114
Opened 2020-12-07 21:45 UTC by MAZamarripa

## Fixes
adds models to power plant dynamic library

## Summary/Motivation:
- add drum1D model, test, and documentation
- add waterpipe model, test, and documentation
## Changes proposed in this PR:
- add drum1D model, test, and documentation
- add waterpipe model, test, and documentation

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2020-12-08 15:26 UTC, andrewlee94 requested changes
A couple of typos, but mostly just suggestions and observations.

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/tests/test_drum1D.py
> +              "linear_solver": "ma27",
Why are we explicitly setting the linear solver here?

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/tests/test_waterpipe.py
> +                               "contraction_expansion_at_end": 'contraction'
It would be good to test the other cases (e.g. expansion in the pipe, plus vapor phase, to make sure the answers look right for those cases too.

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/waterpipe.py
> +        description='water phase',
Should start with a capital.

Should we comment somewhere that mixed phase is not supported?

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/waterpipe.py
> +                doc='Liquid water velocity inside pipe')
Given we also support vapor, should this be "Fluid"  or just "Water" instead of "Liquid water"?

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/waterpipe.py
> +                         doc="Vecolity of fluid inside pipe")
Typo: velocity

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/waterpipe.py
> +        blk.control_volume.release_state(flags, outlvl+1)
`outlvl` should used the basic logger levels - i.e. no +1.

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/waterpipe.py
> +        for t in blk.flowsheet().config.time:
You could make this more compact by using the outlet instead, i.e.:

```
for t in blk.outlet.pressure:
    blk.outlet.pressure[t].fix(value(blk.inlet.pressure[t]))
```

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/drum1D.py
> +    CONFIG.declare("dynamic", ConfigValue(
We should just inherit from the base `CONFIG` block for tthis.

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/drum1D.py
> +            return 1e-4*b.mixer.mixed_state[t].flow_mol == \
Rather than adding fixed scaling factors here, we really should use the scaling tools.

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/drum1D.py
> +        self.drum_di = Param(
I would write this name in full (i.e. diameter instead of di).

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/drum1D.py
> +        self.downcomer_di = Var(
Naming again.

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/drum1D.py
> +            return 0.5*b.drum_di
Do we really need this as a named Expression? Same for many of the following.

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/drum1D.py
> +        # Constant related to Ra,
A comment on what Ra is would probably be useful.

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/drum1D.py
> +        self.pres_amb = Param(initialize=1.0E5, doc="Ambient Pressure")
Should be `pressure_amb` to follow naming conventions,

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/drum1D.py
> +        self.h_in = Var(self.flowsheet().config.time, initialize=1,
I think we should use a more descriptive name here, as "h" can mean many things in process engineering (e.g. specific enthalpy).

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/drum1D.py
> +        self.r = ContinuousSet(bounds=(self.drum_ri, self.drum_ro))
I would use a more descriptive name here too - "radial_domain" perhaps? (The 1D control volume uses length_domain from memory).

2020-12-08 15:26 UTC, andrewlee94 commented on idaes/power_generation/unit_models/drum1D.py
> +            return b.therm_cond_metal / (b.dens_metal * b.cp_metal)
Whilst these are useful for simplifying things later, do we really need to attach them to the model? I.e. why not do:

```
diff_therm_metal = b.therm_cond_metal / (b.dens_metal * b.cp_metal)
```

This achieves the same goal later on, but does not attach the expression to the model, saving us some memory overhead.

Notably, you do this later for the thermal stress calculations.

2020-12-10 21:51 UTC, eslickj requested changes
Looks good.  I just had some minor comments for documentation type things.

2020-12-10 21:51 UTC, eslickj commented on docs/technical_specs/model_libraries/power_generation/unit_models/waterpipe.rst
> +If dynamic = True, the material accumulation holdups are constructed. While, the metal energy holdup is not consideed.
consideed

2020-12-10 21:51 UTC, eslickj commented on docs/technical_specs/model_libraries/power_generation/unit_models/drum1D.rst
> +The heat conduction through insulation is modeled as steady state and no energy holdup or accumulation in the insulation layer is considered. While, the drum metal is actually dynamic with energy hol
Minor Edit

Heat conduction through the insulation is modeled as steady-state, and no energy holdup or accumulation in the insulation layer is considered.  Energy Holdup is accounted for in the drum metal.

2020-12-10 21:51 UTC, eslickj commented on idaes/power_generation/unit_models/drum1D.py
> +                1e-4, default=1)
This is kind of minor, but do you need a line break here to keep the lines short enough?  looks like it may fit on one line.

2020-12-10 23:40 UTC, eslickj approved these changes

2020-12-11 14:32 UTC, andrewlee94 approved these changes
Looks Ok.

2020-12-11 14:48 UTC, Daison2102 approved these changes

2020-12-11 16:37 UTC, merged