Move UI visualizer code out of this repo
IDAES/idaes-pse pull request #1146
Opened 2023-03-25 17:08 UTC by dangunter

Fixes #1129

## Changes proposed in this PR:
- Remove visualizer code
- Add tests to verify correct operation
- Update docs accordingly

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2023-03-27 20:05 UTC, dangunter commented
@andrewlee94 w.r.t. installation instructions I agree, and it was on my to-do list. In a perfect world that would go first. But I have noticed that the current version in main has a bug in the stream table, that didn't seem to lead to any complaints (but looks bad). So in the interest of simplicity, I'd like to just move forward with this PR and then add back instructions once I've got a less borked version of the UI working in the new repo.

2023-03-28 18:27 UTC, lbianchi-lbl requested changes
I've left a suggestion to consider whether we need the added complexity of the wrapper class for this particular case since there's only one call site to handle. Otherwise looks good.

2023-04-06 17:58 UTC, dangunter commented on idaes/core/base/flowsheet_model.py
> +        ui.visualize(self, model_name, **kwargs)
I wanted to allow for other functions, e.g. for diagnostics

2023-05-19 23:16 UTC, CopyDemon commented
I agree with the changes. I think it's a good idea to remove the UI from the main code and add it to its own repo. This will make the code more modular and easier to maintain.

I also agree with Andrew's comment that we should add some sort of pointer to documentation on how to install and set up the UI in the main IDAES docs. This will make it easier for users to get started with the UI. Or we can make some automation install when they install IDAES.

2023-06-06 02:44 UTC, CopyDemon approved these changes

2023-06-22 18:40 UTC, lbianchi-lbl commented
- The conflict should be trivial (files being deleted here were modified in #1133)
- We should be able to merge this soon

2023-06-29 18:50 UTC, lbianchi-lbl commented
Waiting on @dangunter and/or @lbianchi-lbl to fix the git conflicts.

2023-08-19 00:30 UTC, lbianchi-lbl approved these changes

2023-08-24 22:13 UTC, merged