PETSc Tweaks
IDAES/idaes-pse pull request #1235
Opened 2023-08-03 16:11 UTC by dallan-keylogic

## Changes proposed in this PR:
-Only include active blocks when constraints/variables are collected for PETSc solve
-Rename `snes_solver` option to `initial_solver` because the point of the option is to permit use of initial solvers besides snes
-Add symbolic solver labels to initial condition problem
-Get rid of unused list `fix_derivs`

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2023-08-03 16:58 UTC, andrewlee94 requested changes

2023-08-03 16:58 UTC, andrewlee94 commented on idaes/core/solvers/petsc.py
> +    initial_solver="petsc_snes",
Seeing as we are pushing to get backward compatibility tests into place, this look like a place where we are going to need backward compatibility options and warnings. I.e. we need to keep the old options around, and have them raise deprecation warnings if they are used before sending the value to the new argument (and raise an exception if both old and new are provided).

2023-08-03 17:02 UTC, andrewlee94 commented on idaes/core/solvers/petsc.py
> +    initial_solver="petsc_snes",
If it is that new then we are probably OK, but we need to double check that is the case.

2023-08-04 14:49 UTC, eslickj approved these changes
I wanted to make this change when I added the snes_solver option, since it's not necessarily and SNES solver anymore, but I didn't want to break anything.  Once @andrewlee94 gets his deprecation warning, I'm good with this.

2023-08-08 17:56 UTC, andrewlee94 reviewed
Looking good - just a couple of minor comments to avoid some edge cases and be more inline with other deprecations.

2023-08-08 17:56 UTC, andrewlee94 commented on idaes/core/solvers/petsc.py
> +        logger = idaeslog.getIdaesLogger("idaes")
We generally use `logger = idaeslog.getLogger(__name__)` for this - using `__name__` gives more granularity and avoids hard-coded string constants. Also, Pyomo has a deprecation warning function for things like this:

```
from pyomo.common.deprecation import deprecation_warning

deprecation_warning(
    msg=msg, logger=_log, version="2.0.0", remove_in="3.0.0"
)
```

2023-08-08 17:56 UTC, andrewlee94 commented on idaes/core/solvers/petsc.py
> +        )
For clarity to the reader, I would be inclined to move the deprecation warning to immediately after this. This makes it clear why you can;t have both options, and also means that from this point on you don;t have to worry about the deprecation option at all (at the moment, there is the possibility of something happening to the two options between here and when the deprecation is checked).

2023-08-08 18:49 UTC, andrewlee94 approved these changes
LGTM

2023-08-29 17:39 UTC, merged