Add support for dynamics ot MS Contactor
IDAES/idaes-pse pull request #1291
Opened 2023-11-20 16:53 UTC by andrewlee94

## Fixes None

## Summary/Motivation:
This add support for dynamics to the MS Contactor model.

## Changes proposed in this PR:
- Add method to construct volume and volume fraction terms.
- TODO: Add phase fractions to handle multiphase streams
- Added code to construct holdup and accumulation terms as required
- Added accumulation terms to balance equations
- Added units to 0 term in balances for steady-state cases

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2023-11-22 18:19 UTC, agarciadiego approved these changes
LGTM

2023-12-11 21:05 UTC, ArkoprabhoDasgupta approved these changes

2023-12-11 23:04 UTC, dallan-keylogic requested changes
I think partitioning volume between different streams is fine, with the proviso that specific submodels need to provide the constraints that perform that partitioning. However, the phase volume fraction needs to be provided by property packages, and that constraint should be added as part of this model.

2023-12-11 23:04 UTC, dallan-keylogic commented on idaes/models/unit_models/mscontactor.py
> +
Phase volume fraction needs to be given by the property package, and appropriate constraints need to be written here. 

```
def phase_volume_frac_rule(b, p):
    return b.flow_mol_phase[p] * b.dens_mol_phase[p] / sum( b.flow_mol_phase[q] * b.dens_mol_phase[q] for q in b.params.phase_set)
```

2023-12-11 23:04 UTC, dallan-keylogic commented on idaes/models/unit_models/mscontactor.py
> +            )
Consider if you want to index `self.volume` by time now if you have plans to make it time-varying eventually. Having an index that a variable is constant along is easier than trying to add the index after the fact.

2023-12-12 15:23 UTC, dallan-keylogic commented on idaes/models/unit_models/mscontactor.py
> +
Actually, I got mixed up, it should be 
````
def phase_volume_frac_rule(b, p):
    return b.flow_mol_phase[p] * b.vol_mol_phase[p] / sum( b.flow_mol_phase[q] * b.vol_mol_phase[q] for q in b.params.phase_set)
```

2023-12-12 15:56 UTC, dallan-keylogic approved these changes
Upon further reflection, phase fraction is handled appropriately now, its calculation is outsourced to child models of this class, like other unit models involving the `ControlVolume`.

2023-12-12 16:30 UTC, merged