Wrap 0D Fixed Bed TSA unit model in `extra_models/fixed_bed_tsa0d` for Flowsheet Runner UI
IDAES/idaes-pse pull request #1493
Opened 2024-10-02 14:56 UTC by dangunter

## Fixes

## Summary/Motivation:
Initial UI wrapper for IDAES

## Changes proposed in this PR:
- Wrap the model so it can be displayed in the Flowsheet Runner UI

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2024-10-03 16:13 UTC, dangunter commented
One issue I see immediately is that the "model options" for the TSA has a number of values and they will _probably_ be changed at the same time / along with the model's other parameters and variables. However currently the UI sets these options in different, initial step, as shown by this screenshot for a watertap model:

![image](https://github.com/user-attachments/assets/b6a6a251-70d7-4a25-b3ff-fa30ad2d131a)

This is, imho not ideal. We should have these sorts of model options more included in the main configuration page, even though they are not Pyomo vars.

@Daison2102 Do I have this roughly right about the `FixedBedTSA0D` model class?
@sspoon thoughts on the design?

2024-10-03 17:56 UTC, MichaelPesce commented
@dangunter the original purpose of those options were to allow for pre-build configurations, so it had made sense to be able to view them before running the build. however, they should also be available from the main workflow (after build step), where the model can be re-built with different model configurations

2024-10-03 20:31 UTC, dangunter commented
@MichaelPesce ok, though I think it might be better to have them as normal parameters

2024-11-26 19:23 UTC, lbianchi-lbl requested changes
Before merging, we should (* denotes items that are not strictly required):

- [ ] Add a dev dependency on `idaes-flowsheet-processor @ git+https://github.com/watertap-org/idaes-flowsheet-processor@0.1.dev1`
- [x] (*) Add an entry point in `setup.py` pointing to the `idaes.model_extra.temperature_swing_adsorption.fixed_bed_tsa0d_ui` module under the `idaes.flowsheets` group
- [ ] (*) Enable testing using the `idaes-flowsheets` pytest plugin

2024-11-26 19:23 UTC, lbianchi-lbl commented on idaes/models_extra/temperature_swing_adsorption/tests/test_fixed_bed_tsa0d_ui.py
> +from idaes.models_extra.temperature_swing_adsorption.util import tsa_summary
```suggestion
from idaes.models_extra.temperature_swing_adsorption.util import tsa_summary
pytest.importorskip("idaes_flowsheet_processor.api", reason="idaes-flowsheet-processor must be installed to run this test")
```

2024-12-11 13:00 UTC, MichaelPesce commented
@lbianchi-lbl @dangunter in order to get this working in the `idaes-electron-build`, we have to change the import `from watertap.ui import fsapi as api` to `from idaes_flowsheet_processor import api`, as suggested above

2024-12-11 13:47 UTC, lbianchi-lbl commented
> @lbianchi-lbl @dangunter in order to get this working in the `idaes-electron-build`, we have to change the import `from watertap.ui import fsapi as api` to `from idaes_flowsheet_processor import api`, as suggested above

@MichaelPesce done in d0209e7

2025-02-13 19:45 UTC, lbianchi-lbl approved these changes

2025-02-14 16:31 UTC, merged