Add utilities for scaled Jacobian and condition number
IDAES/idaes-pse pull request #315
Opened 2021-04-29 21:02 UTC by eslickj

Add some utility functions so you can get the scaled and unscaled Jacobian and condition numbers.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-04-30 12:51 UTC, andrewlee94 requested changes
One minor comment from me.

2021-04-30 12:51 UTC, andrewlee94 commented on idaes/core/util/scaling.py
> +    Get the Jacobian matrix at the current model values.
I think this was copied from the previous method and not updated.

2021-04-30 13:42 UTC, andrewlee94 requested changes
A couple more typos.

2021-04-30 13:42 UTC, andrewlee94 commented on idaes/core/util/scaling.py
> +    Get the condion number of the scaled or unscaled Jacobian matirx of a model.
Typos: condition, matrix

2021-04-30 14:00 UTC, andrewlee94 approved these changes
Looks good to me.

2021-04-30 15:05 UTC, eslickj commented
@nareshsusarla, thanks I didn't know about the warning, but it's probably fine.  The matrix inversion will probably take so much longer than anything else that taking some extra time computing the norm is probably nothing.  I'm a bit worried that this will take a really long time or fail for big and/or poorly conditioned problems, but we'll see how it goes.

2021-05-06 18:56 UTC, nareshsusarla approved these changes

2021-05-07 02:28 UTC, merged