Adding a method to compute heat capacity ratio in generic property pack
IDAES/idaes-pse pull request #364
Opened 2021-05-26 21:24 UTC by nareshsusarla

## Fixes

## Summary/Motivation:
Adding a method for computing heat capacity ratio in the generic property package and the EoS base class

## Changes proposed in this PR:
- added method to compute heat capacity ratio in eos_base.py `def heat_capacity_ratio(b, p)`
-added support for the same in generic_property.py

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-05-27 13:11 UTC, andrewlee94 requested changes
A couple of comments on component naming, plus tests are needed to prove that this works. Updating the docs would also be a good idea.

2021-05-27 13:11 UTC, andrewlee94 commented on idaes/generic_models/properties/core/eos/eos_base.py
> +    def heat_capacity_ratio(b, p):
This should be `heat_capacity_ratio_phase`.

2021-05-27 13:11 UTC, andrewlee94 commented on idaes/generic_models/properties/core/generic/generic_property.py
> +             'heat_capacity_ratio': {'method': '_heat_capacity_ratio'},
This should be `heat_capacity_ratio_phase` also,

2021-05-27 13:11 UTC, andrewlee94 commented on idaes/generic_models/properties/core/generic/generic_property.py
> +    def _heat_capacity_ratio(self):
As above.

2021-05-27 13:11 UTC, andrewlee94 commented on idaes/generic_models/properties/core/generic/generic_property.py
> +                doc="Heat capacity ratio")
Add "by phase" or something here to indicate that this is indexed by phase.

2021-06-02 13:46 UTC, eslickj reviewed
Looks good to me.  Just add a test and I'll approve.  Hopefully there are existing heat capacity tests you can use to easily write a test.

2021-06-03 18:50 UTC, eslickj approved these changes

2021-06-03 19:01 UTC, andrewlee94 approved these changes
This looks good now, but we should hold off merging until the release process is completed.

2021-06-03 19:01 UTC, andrewlee94 commented on idaes/generic_models/properties/core/eos/tests/test_ideal.py
> +        assert str(Ideal.heat_capacity_ratio_phase(m.props[1], p)) == (
Probably not for this PR, but there really should be a set of tests for EoSBase as well, which should include this.

2021-06-03 20:58 UTC, merged