CO2-H2O-MEA Property Package
IDAES/idaes-pse pull request #373
Opened 2021-05-31 22:38 UTC by anujad95

## Fixes
NA

## Summary/Motivation:
Develop a property package for CO2-H2O-MEA system, modeled as an ideal VLE to begin with. 

## Changes proposed in this PR:
Adding a config dictionary file, along with additional scripts for custom methods, and a basic test for property package setup.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-06-03 16:59 UTC, andrewlee94 requested changes

2021-06-03 16:59 UTC, andrewlee94 commented on idaes/generic_models/properties/core/examples/CO2_H2O_MEA_Ideal_VLE_Final.py
> +##############################################################################
I think the "Final" needs to be removed from the file name.

2021-06-03 16:59 UTC, andrewlee94 commented on idaes/generic_models/properties/core/examples/CO2_H2O_MEA_Ideal_VLE_Final.py
> +from idaes.generic_models.properties.core.examples import CustomMethods_Final,\
1. I think these custom methods need more descriptive names.
2. I don't think these should be in separate files, and definitely shouldn't be importable directly from `examples`.

2021-06-03 16:59 UTC, andrewlee94 commented on idaes/generic_models/properties/core/examples/CustomMethods_Final.py
> +Custom Methods for calculating pure component properties of MEA, H2O:
Need to explain why are these custom methods are required.

2021-06-03 16:59 UTC, andrewlee94 commented on idaes/generic_models/properties/core/examples/CustomMethods2_Final.py
> +class henrys_constant_co2_h2o():
There will be a PR soon that adds support for Henry's components, so we should hold on on this PR until that is ready.

2021-06-03 16:59 UTC, andrewlee94 commented on idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_MEA_Ideal_VLE.py
> +import numpy as np
Are most of these actually needed? I do not see `np` being used anywhere for one.

2021-06-03 16:59 UTC, andrewlee94 commented on idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_MEA_Ideal_VLE.py
> +from pyomo.common.unittest import assertStructuredAlmostEqual
Examples don't really need to check this unless there is a good reason for it.

2021-06-03 16:59 UTC, andrewlee94 commented on idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_MEA_Ideal_VLE.py
> +from idaes.core import (MaterialBalanceType,
Do you actually need the balance type Enums?

2021-06-03 16:59 UTC, andrewlee94 commented on idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_MEA_Ideal_VLE.py
> +    def test_build(self, model):
Examples don't really need to test most of this stuff. Just focus on an application case and check the results.

2021-06-03 16:59 UTC, andrewlee94 commented on idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_MEA_Ideal_VLE.py
> +    @pytest.mark.initialize
The `initialize`, `build` and `solver` marks are deprecated, so you can remove them.

2021-06-03 16:59 UTC, andrewlee94 commented on idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_MEA_Ideal_VLE.py
> +        assert results.solver.status == SolverStatus.ok
You need to compare the model results to something from literature, otherwise we have no way of knowing if the model is right.

2021-06-17 18:46 UTC, ksbeattie commented
@anujad95, any update on this?

2021-07-08 18:29 UTC, ksbeattie commented
@anujad95 any update on this?

2021-07-08 18:48 UTC, anujad95 commented
@ksbeattie no update yet, I will continue working on this.

2021-08-13 00:00 UTC, lbianchi-lbl commented
@anujad95 we're looking at open PRs in preparation for the August release. Is this work expected to be completed in the next few days? Otherwise, we can keep tracking this PR as part of the November release.

2021-09-30 18:38 UTC, ksbeattie commented
@anujad95, can you take a look at @andrewlee94 suggestions?

2021-11-04 18:27 UTC, ksbeattie commented
@anujad95 is this still possibly for the Nov release?

2021-11-04 18:30 UTC, andrewlee94 commented
@anujad95 Is this still needed after the MEA property packages have been clean up?

2021-11-18 19:57 UTC, ksbeattie commented
@anujad95, this appears to be old enough to be out of date now.

2021-11-18 19:57 UTC, closed without merging