Draft: Adding mock units to stream_table
IDAES/idaes-pse pull request #465
Opened 2021-08-18 18:48 UTC by elbashandy

## Summary/Motivation:
Adding units to the stream table view that shows up on the UI page. The units are generated randomly using the pyomo library to read the `derived_units` units from the FlowSheetBlock.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-08-23 19:59 UTC, dangunter commented
This PR should be changed to be adding units, even if it is starting as mock units. A PR for adding mock units would never get merged.

2021-09-09 18:14 UTC, dangunter requested changes

2021-09-09 18:14 UTC, dangunter commented on idaes/ui/flowsheet.py
> +            def apply_html(value, style=''):
Wouldn't this make more sense in the JS client? Seems wrong to hardcode display styles in the server.

2021-09-09 18:14 UTC, dangunter commented on idaes/ui/fsvis/static/js/stream_table.js
>              if (column_header !== "") {
could reduce indentation by doing a continue here instead

2021-09-09 18:14 UTC, dangunter commented on idaes/ui/fsvis/static/js/stream_table.js
>                  if (column_header === "Variable") {
This is where you could take the plain text sent from the server and make it into appropriate HTML, e.g. if the server sent "VariableName,m/s^2" you could split on the comma and format.

2021-09-09 18:14 UTC, dangunter commented on idaes/ui/fsvis/static/css/main.css
> +
Please add some comments here saying what these affect and why. I would suggest more specific class names like "streamtable-variable"

2021-09-21 16:33 UTC, dangunter commented on idaes/core/util/tables.py
>                  if i is None:
from here to line 264 seems like duplicated code except for the difference in the key. why not do that up front and use the same logic, i.e. `units_key = k if is None else f"{k} {i}"` then use 'units_key' in place of 'k' and not require the `if i is None` decision

2021-09-28 19:06 UTC, dangunter approved these changes
LGTM

2021-09-29 18:36 UTC, lbianchi-lbl approved these changes
For testing, I called `idaes.ui.fsvis.visualize()` on the flowsheet created by `idaes.ui.tests.test_flowsheet.demo_flowsheet()`, and checked the stream table in the web UI. The units (and therefore this PR) LGTM!

![image](https://user-images.githubusercontent.com/48035537/135328385-7d692952-5b8d-4fcc-a097-95e77c59511e.png)

2021-09-30 17:05 UTC, merged