Multi connections for the mixer component as a 'target' model
IDAES/idaes-pse pull request #598
Opened 2021-11-16 15:46 UTC by elbashandy

## Fixes

- Supporting multi-connection links for the 'Mixer' component as a destination/target end.
- Refactored the way we load ports that links connect to in order to support the multi-connection feature.

## Summary/Motivation:
Providing an initial way for developers to control the orthogonal path that links should go through when connecting components. This provides a flexible way for developers to change the ways a Unit Model  (e.g. Mixer) should be connected to by links/edges. 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-12-06 16:14 UTC, dangunter commented
@elbashandy I am seeing test failures in CI. Are you seeing those locally?

2021-12-07 16:14 UTC, dangunter commented
@elbashandy I tried a flowsheet with the mixer unit and it doesn't show any differently

2021-12-07 18:51 UTC, dangunter requested changes
Minor documentation changes requested

2021-12-07 18:51 UTC, dangunter commented on idaes/ui/fsvis/static/js/cell_config.js
> +
Could you add a file header that describes what this file does

2021-12-07 18:51 UTC, dangunter commented on idaes/ui/fsvis/static/js/main.js
>  import { Paper } from './paper.js';
Could you add a file header that says what this file is for

2021-12-07 18:51 UTC, dangunter commented on idaes/ui/icons.py
>      _mapping = {
Could you add a TODO for moving this mapping to its own directory/files

2021-12-16 17:10 UTC, dangunter approved these changes
LGTM

2021-12-20 19:35 UTC, ksbeattie approved these changes
LGTM

2021-12-20 22:02 UTC, merged