Correction to the MEA solvent property package and column
IDAES/idaes-pse pull request #914
Opened 2022-07-18 16:14 UTC by anujad95

## Fixes
MEA_solvent property package and solvent_column unit model

## Summary/Motivation:
Corrections to the molar enthalpy calculation and MEA enthalpy of vaporization in the MEA_solvent property package, along with the enthalpy transfer term in solvent_column unit model

## Changes proposed in this PR:
- Converting the temperature used in the molar enthalpy calculation for liquid phase components, from K to deg C
- Including the value for MEA enthalpy of vaporization to ensure accurate molar enthalpy calculation
- Correcting the enthalpy transfer term in solvent_column unit model

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-07-18 16:37 UTC, andrewlee94 commented on idaes/models_extra/column_models/properties/MEA_solvent.py
> +                "dh_vap": 54000,
Is this actually used anywhere?

2022-08-04 18:25 UTC, ksbeattie commented
@anujad95 is this ready for a re-review?

2022-08-08 15:22 UTC, andrewlee94 commented
@anujad95 There are a lot of failing tests in this PR which need to be fixed before we can review it. You should also update the branch as well.

2022-08-11 18:35 UTC, ksbeattie commented
I've updated this branch from main in hopes that this can be merge in time for the Aug release (meaning next week).

2022-08-23 13:25 UTC, andrewlee94 requested changes
This mostly looks good but I would like to confirm that the changes in model results we are seeing for the heat exchanger models have been verified against some other source.

2022-08-23 13:25 UTC, andrewlee94 commented on idaes/models_extra/column_models/tests/test_solvent_condenser.py
> +        xfrm = TransformationFactory("contrib.strip_var_bounds")
Could you comment on why this is needed? An inline comment in the code might also be good for future reference.

2022-08-23 13:25 UTC, andrewlee94 commented on idaes/models_extra/column_models/tests/test_plate_heat_exchanger.py
> +        assert pytest.approx(345.612, rel=1e-5) == value(
These are some significant changes in the model results - have you confirmed that you have verified these changes are correct?

2022-08-24 19:26 UTC, andrewlee94 approved these changes

2022-08-25 12:19 UTC, aostace01 approved these changes
Looks good to me.

2022-08-25 13:09 UTC, merged