Scaling dynamics
IDAES/idaes-pse pull request #950
Opened 2022-09-09 20:41 UTC by dallan-keylogic

## Summary/Motivation:

Add scaling utility that allows users to quickly scale time `DerivativeVars` and time discretization equations with a single global time scaling factor and the state variable scaling factors.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2022-09-19 14:20 UTC, dallan-keylogic commented
@Robbybp @blnicho @eslickj Could yinz take a look at this PR sometime soon? I've got another PR coming along that depends on this one.

2022-09-20 22:41 UTC, eslickj approved these changes

2022-09-20 22:41 UTC, eslickj commented on idaes/core/solvers/petsc.py
> +        # tj = None  # trajectory data
Go ahead and delete

2022-09-22 20:11 UTC, dallan-keylogic commented on idaes/core/solvers/tests/test_petsc.py
> +# def test_petsc_read_trajectory():
It's a copy of an existing test that I was probably going to modify, before deciding to do something else. It's been removed.

2022-09-22 20:41 UTC, blnicho approved these changes

2022-09-22 21:15 UTC, Robbybp requested changes
I think I see some bugs in edge cases. Let me know if I missed something.

2022-09-26 14:53 UTC, dallan-keylogic commented on idaes/core/util/scaling.py
> +                    idx_time = idx_set_list.index(time_set)
Thank you for this example. I've added a test to ensure this edge case is handled correctly.

2022-09-26 16:47 UTC, Robbybp commented on idaes/core/util/scaling.py
> +                        t = idx
This is not designed to work on time-indexed blocks. However, I believe DerivativeVars (and their associated states) and all constraints created by DAE will always be explicitly indexed by time.

2022-09-26 16:48 UTC, Robbybp approved these changes
Looks good assuming tests pass.

2022-09-26 19:11 UTC, dallan-keylogic commented
@ksbeattie @lbianchi-lbl @bpaul4 Any idea why the examples tests are failing?

2022-09-26 19:22 UTC, bpaul4 commented
@dallan-keylogic we recently added `idaes-examples` as a package on the examples-pse side to internally import modules for some examples, and it looks like the idaes-pse is not automatically installing it when getting the examples. We should be able to edit `requirements.txt` to do that, so it's installed for users as well when they update IDAES.

2022-09-26 19:28 UTC, bpaul4 commented
@lbianchi-lbl I see that `requirements-dev.txt` is installing some editable dependencies [here](https://github.com/IDAES/idaes-pse/blob/c7720427818a0907e83777d7e4610f8bf003d418/requirements-dev.txt#L36), we probably need to update this or add it to CI workflow.

I support manually merging @dallan-keylogic's PR since it is unrelated to the issue and all non-examples tests are passing.

2022-09-26 23:20 UTC, merged