Power plant boiler fire side and steam heater models, docs, and tests
IDAES/idaes-pse pull request #98
Opened 2020-11-24 15:20 UTC by MAZamarripa

**NOTE:** When this PR is approved, you *must* do the following so it can be merged:
* Add the "approved" tag to the pull-request
* Trigger tests by pushing a commit or manually re-running in CircleCI

See [this wiki page](https://github.com/IDAES/idaes-dev/wiki/Github-Pull-Request-Workflow-with-Approval-Tag) for details.

----
## Fixes
contributes models to the power plant library

## Summary/Motivation:
WIP: complete power plant library

## Changes proposed in this PR:
- adding boiler fire side model, test, and documentation
- adding steamheater model, test, and documentation

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

----

## Reviewer Checklist
* Reviewer 1
- [ ] Tests: do they pass, do they cover functionality, are they understandable?
- [ ] Documentation: is the code commented, are there user-level docs where needed?
* Reviewer 2
- [ ] Tests: do they pass, do they cover functionality, are they understandable?
- [ ] Documentation: is the code commented, are there user-level docs where needed?

2020-11-24 17:52 UTC, andrewlee94 requested changes
A lot of comments but a lot are just observations that do not need to be fixed right now. There were a couple of typos I noticed and couple of places where we can do things better, but otherwise I think this is good.

2020-11-24 17:52 UTC, andrewlee94 commented on idaes/power_generation/unit_models/steamheater.py
> +        @self.Expression(doc="Half of fin thickness")
I do have to ask if we really need a named `Expression` for this.

2020-11-24 17:52 UTC, andrewlee94 commented on idaes/power_generation/unit_models/steamheater.py
> +                initialize=1.3,
For the future, but these would probably be better as `Vars` to allow for parameter estimation (slag conductivity strikes me as something we would want to estimate).

2020-11-24 17:54 UTC, andrewlee94 submitted a review, later dismissed

2020-11-25 19:11 UTC, andrewlee94 reviewed
A couple of minor observations.

2020-11-25 19:11 UTC, andrewlee94 commented on idaes/power_generation/unit_models/boiler_fireside.py
> +4. Moisture mass fration in raw coal is a user input and
Typo: fraction.

2020-11-25 19:11 UTC, andrewlee94 commented on idaes/power_generation/unit_models/boiler_fireside.py
> +            raise ConfigurationError('user needs to provide '
Error messages really should start with a capital, and it is probably helpful to tell the user where the error occurred. I.e.

`raise ConfiguraitonError('{} Some message here'.format(self.name))`

This way, the user knows which model they need to fix.

2020-11-25 19:19 UTC, eslickj commented
Looks like there is a list in a doc string that doesn't end with a new line:

/home/runner/work/idaes-pse/idaes-pse/idaes/power_generation/unit_models/boiler_fireside.py:docstring of idaes.power_generation.unit_models.boiler_fireside:34: WARNING: Enumerated list ends without a blank line; unexpected unindent.

2020-11-25 19:22 UTC, andrewlee94 commented
I think the issue is on line 47 of boiler_fireside.py. Try not indenting the last line of the numbered list first.

2020-11-30 15:29 UTC, eslickj commented
I think this looks good.  Once the tests pass, I'll approve.

2020-11-30 17:38 UTC, jghouse88 approved these changes
LGTM (Rubber stamping)

2020-11-30 22:28 UTC, eslickj approved these changes

2020-12-02 17:13 UTC, merged